version: "3.9"

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: afiliados
      POSTGRES_USER: afiliados
      POSTGRES_PASSWORD: afiliados
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U afiliados"]
      interval: 5s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  app:
    build: .
    environment:
      - APP_ENV=dev
      - DATABASE_URL=postgresql+psycopg2://afiliados:afiliados@db:5432/afiliados
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - UVICORN_PORT=8080
    depends_on:
      - db
      - rabbitmq
    ports:
      - "8080:8080"
