from uuid import UUID
from core.seedworks.repositorios import Repositorio
from .entidades import Colaboracion

class RepositorioColaboraciones(Repositorio):
    """Interfaz de repositorio para la raíz de agregación Colaboracion"""

    def obtener_por_id(self, id: UUID) -> Colaboracion: ...
    def obtener_todos(self) -> list[Colaboracion]: ...
    def agregar(self, entity: Colaboracion): ...
    def actualizar(self, entity: Colaboracion): ...
    def eliminar(self, entity_id: UUID): ...
